# Topic is the highest level of organization. It serves as a container
# for datasets that should live together in their own schema.
name = "milmi"
description = "Cleans, standardizes and loads the MILMI dataset we receive from the state (or painstakingly download)."
schema = "milmi"

[tables.milmi_employers]
name="milmi_employers"
description = ""
unit_of_analysis = ""
universe = ""
owner = ""
collector = ""
# collection_method = "Leave commented if not using"
collection_reason = ""
source_url = ""
# notes = "Leave commented if not using"
# use_conditions = "Leave commented if not using"
# cadence = "Leave commented if not using"

[[tables.milmi_employers.variables]]
name = "id"
description = ""
parent_variable = ""
# suppression_threshold = "Leave commented if not using."
# standard = "Leave commented if not using."

[[tables.milmi_employers.variables]]
name = "name"
description = ""
parent_variable = ""
# suppression_threshold = "Leave commented if not using."
# standard = "Leave commented if not using."

[[tables.milmi_employers.variables]]
name = "address"
description = ""
parent_variable = ""
# suppression_threshold = "Leave commented if not using."
# standard = "Leave commented if not using."

[[tables.milmi_employers.variables]]
name = "phone"
description = ""
parent_variable = ""
# suppression_threshold = "Leave commented if not using."
# standard = "Leave commented if not using."

[[tables.milmi_employers.variables]]
name = "website"
description = ""
parent_variable = ""
# suppression_threshold = "Leave commented if not using."
# standard = "Leave commented if not using."

[[tables.milmi_employers.variables]]
name = "business_description"
description = ""
parent_variable = ""
# suppression_threshold = "Leave commented if not using."
# standard = "Leave commented if not using."

[[tables.milmi_employers.variables]]
name = "num_employees"
description = ""
parent_variable = ""
# suppression_threshold = "Leave commented if not using."
# standard = "Leave commented if not using."

[[tables.milmi_employers.variables]]
name = "lat"
description = ""
parent_variable = ""
# suppression_threshold = "Leave commented if not using."
# standard = "Leave commented if not using."

[[tables.milmi_employers.variables]]
name = "lon"
description = ""
parent_variable = ""
# suppression_threshold = "Leave commented if not using."
# standard = "Leave commented if not using."

[[tables.milmi_employers.variables]]
name = "geometry"
description = ""
parent_variable = ""
# suppression_threshold = "Leave commented if not using."
# standard = "Leave commented if not using."

[[tables.milmi_employers.variables]]
name = "county"
description = ""
parent_variable = ""
# suppression_threshold = "Leave commented if not using."
# standard = "Leave commented if not using."

[[tables.milmi_employers.variables]]
name = "start"
description = ""
parent_variable = ""
# suppression_threshold = "Leave commented if not using."
# standard = "Leave commented if not using."

[[tables.milmi_employers.variables]]
name = "end"
description = ""
parent_variable = ""
# suppression_threshold = "Leave commented if not using."
# standard = "Leave commented if not using."

[tables.milmi_employers.editions.2025-01-01]
edition_date = "2025-01-01"
notes = "2025 upload of the milmi dataset -- available for counties Wayne, Oakland, Macomb, St Clair, Monroe, Calhoun, Washtenaw"
raw_path = "/home/michael/projects/new/system/data/milmi/EMPDB_request.xlsx"
start = "2024-01-01" 
end = "9999-12-31" # Forever
published = "2024-01-01"
acquired = "2025-01-29" 
