# Topic is the highest level of organization. It serves as a container
# for datasets that should live together in their own schema.
name = "milmi"
description = "Cleans, standardizes and loads the MILMI dataset we receive from the state (or painstakingly download)."
schema = "milmi"

[tables.milmi_employers]
name="milmi_employers"
description = "The list of Michigan Employers (not all counties) gathered by Data Axel."
unit_of_analysis = "Businesses with at least one employee"
universe = "Employers in counties: Wayne, Oakland, Macomb, Livingston, Monroe, Washtenaw, Calhoun"
owner = "State of Michigan"
collector = "Data Axel"
collection_reason = "Labor Market Research"
source_url = "https://milmi.org/"
notes = "We get this by emailing someone from the state -- we can't request the whole state, so we request key counties."
# use_conditions = "Leave commented if not using"
cadence = "Yearly-ish"

[[tables.milmi_employers.variables]]
name = "id"
description = "The D3-generated id for the business"

[[tables.milmi_employers.variables]]
name = "name"
description = "The business name"

[[tables.milmi_employers.variables]]
name = "address"
description = "The business address"

[[tables.milmi_employers.variables]]
name = "city"
description = "The business address"

[[tables.milmi_employers.variables]]
name = "state"
description = "The business address state"

[[tables.milmi_employers.variables]]
name = "zip_code"
description = "The business address zip code"

[[tables.milmi_employers.variables]]
name = "zip_code_2"
description = "The business address zip code extension"

[[tables.milmi_employers.variables]]
name = "business_description"
description = "The description of the business"

[[tables.milmi_employers.variables]]
name = "naics"
description = "The NAICS code representing the business's industry category"
standard = "NAICS"

[[tables.milmi_employers.variables]]
name = "employment_size"
description = "The size of the business coded with letters A - K"

[[tables.milmi_employers.variables]]
name = "employment_size_range"
description = "The range represented by the letter in the business_size field"

[[tables.milmi_employers.variables]]
name = "employment_size_value"
description = "The exact (?) number of employees of the business (or maybe an estimate, unsure -- MV)"

[[tables.milmi_employers.variables]]
name = "county"
description = "The county of the business"

[[tables.milmi_employers.variables]]
name = "year"
description = "The year of the dataset"


[tables.milmi_employers.editions.2025-01-01]
edition_date = "2025-01-01"
notes = "2025 upload of the milmi dataset -- available for counties Wayne, Oakland, Macomb, St Clair, Monroe, Calhoun, Washtenaw, Livingston"
raw_path = "V:\\DATA\\Business and employment\\MILMI\\Data\\2025\\Raw\\EMPDB_request.xlsx"
start = "2024-01-01" 
end = "9999-12-31" # Forever
published = "2024-01-01"
acquired = "2025-01-29" 
